"""Generate Lindhard-Scharff electronic stopping power tables for LAMMPS `fix electron/stopping`.

Produces dE/dx (eV/Å) vs E (eV) tables for a given heavy ion + carbon recoils in diamond.

Output format (matches LAMMPS fix electron/stopping expectations):
    # comment lines allowed
    E_eV   dE/dx_type1_eV_per_A   dE/dx_type2_eV_per_A
where type 1 = C (recoils inside diamond), type 2 = the heavy ion (Sn or Pb).

Lindhard-Scharff (LSS) model, valid for v < v_0 * Z1^(2/3) (i.e. below the stopping-
power maximum). For Sn and Pb in C, this covers the full energy range used here
(20-170 keV).

    S_e(E) = K * sqrt(E),
    K = 1.212 * Z1^(7/6) * Z2 * n_target / ((Z1^(2/3) + Z2^(2/3))^(3/2) * sqrt(M1))

with E in eV, S_e in eV/A, n_target in atoms/A^3.

WARNING: This is an analytic approximation. For publication-quality work the table
should be replaced with values from SRIM/SDTrimSP or a TDDFT-derived stopping curve
for the specific ion-target combination. Lindhard-Scharff systematically over-predicts
stopping for heavy ions near the stopping-power maximum.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

# Diamond target (carbon)
Z_C = 6
M_C = 12.011
RHO_DIAMOND = 3.515  # g/cm^3
N_AVOGADRO = 6.02214076e23
N_C = RHO_DIAMOND / M_C * N_AVOGADRO / 1.0e24  # atoms / A^3 ~= 0.1764


def lindhard_K(z1: float, m1: float, z2: float = Z_C, n: float = N_C) -> float:
    return (
        1.212
        * z1 ** (7 / 6)
        * z2
        * n
        / ((z1 ** (2 / 3) + z2 ** (2 / 3)) ** 1.5 * np.sqrt(m1))
    )


def write_table(
    z_ion: float,
    m_ion: float,
    energies_eV: np.ndarray,
    output_path: Path,
    species_label: str,
) -> None:
    k_carbon = lindhard_K(Z_C, M_C)
    k_ion = lindhard_K(z_ion, m_ion)
    se_carbon = k_carbon * np.sqrt(energies_eV)
    se_ion = k_ion * np.sqrt(energies_eV)
    with output_path.open("w") as f:
        f.write(
            f"# Lindhard-Scharff electronic stopping table for {species_label} "
            f"(Z={z_ion}, M={m_ion}) in diamond.\n"
        )
        f.write("# Generated by potentials/generate_stopping.py — see docstring for caveats.\n")
        f.write("# Columns: E(eV)  dE/dx_C(eV/A)  dE/dx_ion(eV/A)\n")
        for energy, sc, si in zip(energies_eV, se_carbon, se_ion):
            f.write(f"{energy:.6e}  {sc:.6e}  {si:.6e}\n")


def main() -> None:
    energies = np.geomspace(1.0, 5.0e5, 200)  # 1 eV - 500 keV, log-spaced
    here = Path(__file__).parent
    write_table(50, 118.71, energies, here / "electron-stopping-sn.dat", "Sn")
    write_table(82, 207.2, energies, here / "electron-stopping-pb.dat", "Pb")
    print(f"Wrote stopping tables to {here}")


if __name__ == "__main__":
    main()
