"""Generate Lindhard-Scharff electronic stopping power tables for LAMMPS `fix electron/stopping`.

Produces dE/dx (eV/A) vs E (eV) tables for a heavy ion + carbon recoils in diamond.

Output format (matches LAMMPS fix electron/stopping expectations):
    # comment lines allowed
    E_eV   dE/dx_type1_eV_per_A   dE/dx_type2_eV_per_A
where type 1 = C (recoils inside diamond), type 2 = the heavy ion (Sn or Pb).

Lindhard-Scharff (LSS) model, valid for v < v0 * Z1^(2/3) (below the stopping-power
maximum), which covers 20-60 keV Sn/Pb comfortably.  Canonical form (Nastasi/Was):

    S_e = k_L * sqrt(E[keV])            [1e-15 eV cm^2 / atom]
    k_L = 1.212 * Z1^(7/6) * Z2 / ((Z1^(2/3) + Z2^(2/3))^(3/2) * sqrt(M1))

Conversion to eV/A:  S[eV/A] = S[1e-15 eV cm^2] * n[atoms/cm^3] * 1e-15 * 1e-8.

UNIT TRAP (this bit us once): the 1.212 constant requires E in **keV** and the
density conversion needs the full areal-density factor.  Using sqrt(E in eV)
with n in atoms/A^3 looks dimensionally plausible and silently overestimates
S_e by exactly sqrt(1000)/10 = 3.162.  main() self-tests against a hand-checked
reference value so this cannot silently regress.

Accuracy caveats (state in the paper):
- LSS is +-30-50% absolute for heavy slow ions; Z1 oscillations mean SRIM values
  for Sn in C run ~30% below LSS.  For publication-grade absolute depths,
  replace these tables with SRIM/SDTrimSP output (same file format).
- A single S_e(E) ignores the impact-parameter dependence: channeled ions see
  a lower electron density than the random medium, so the channeled advantage
  is *underestimated* with these tables.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

# Diamond target (carbon)
Z_C = 6
M_C = 12.011
RHO_DIAMOND = 3.515                                   # g/cm^3
N_AVOGADRO = 6.02214076e23
N_C_CM3 = RHO_DIAMOND / M_C * N_AVOGADRO              # atoms/cm^3 ~= 1.763e23


def lindhard_kL(z1: float, m1: float, z2: float = Z_C) -> float:
    """LSS prefactor k_L in 1e-15 eV cm^2/atom per sqrt(keV)."""
    return (
        1.212
        * z1 ** (7 / 6)
        * z2
        / ((z1 ** (2 / 3) + z2 ** (2 / 3)) ** 1.5 * np.sqrt(m1))
    )


def stopping_eV_per_A(E_eV, z1: float, m1: float, n_cm3: float = N_C_CM3):
    """Electronic stopping power in eV/A for a projectile (z1, m1) in diamond."""
    E_keV = np.asarray(E_eV, dtype=float) / 1000.0
    return lindhard_kL(z1, m1) * np.sqrt(E_keV) * n_cm3 * 1.0e-23


def write_table(
    z_ion: float,
    m_ion: float,
    energies_eV: np.ndarray,
    output_path: Path,
    species_label: str,
) -> None:
    se_carbon = stopping_eV_per_A(energies_eV, Z_C, M_C)
    se_ion = stopping_eV_per_A(energies_eV, z_ion, m_ion)
    with output_path.open("w") as f:
        f.write(
            f"# Lindhard-Scharff electronic stopping table for {species_label} "
            f"(Z={z_ion}, M={m_ion}) in diamond (n = {N_C_CM3:.4e} cm^-3).\n"
        )
        f.write("# Generated by potentials/generate_stopping.py -- see docstring for caveats.\n")
        f.write("# Columns: E(eV)  dE/dx_C(eV/A)  dE/dx_ion(eV/A)\n")
        for energy, sc, si in zip(energies_eV, se_carbon, se_ion):
            f.write(f"{energy:.6e}  {sc:.6e}  {si:.6e}\n")


def self_test() -> None:
    """Hand-checked references; abort rather than write wrong tables."""
    # 60 keV Sn in diamond: k_L = 0.924, S_e = 0.924*sqrt(60)*1.763e23*1e-23 = 12.6 eV/A
    s_sn = float(stopping_eV_per_A(60e3, 50, 118.71))
    assert abs(s_sn - 12.61) < 0.1, f"Sn 60 keV: got {s_sn:.3f}, expected 12.61 eV/A"
    # C self-stopping: k_L(C in C) = 1.000; S_e(1 keV) = 1.763 eV/A
    s_c = float(stopping_eV_per_A(1e3, Z_C, M_C))
    assert abs(s_c - 1.763) < 0.02, f"C 1 keV: got {s_c:.3f}, expected 1.763 eV/A"


def main() -> None:
    self_test()
    energies = np.geomspace(1.0, 5.0e5, 200)  # 1 eV - 500 keV, log-spaced
    here = Path(__file__).parent
    write_table(50, 118.71, energies, here / "electron-stopping-sn.dat", "Sn")
    write_table(82, 207.2, energies, here / "electron-stopping-pb.dat", "Pb")
    print("Self-test passed.  Reference values:")
    for label, z, m in (("Sn", 50, 118.71), ("Pb", 82, 207.2)):
        for e in (20e3, 35e3, 60e3):
            print(f"  {label} {e/1e3:5.0f} keV : {float(stopping_eV_per_A(e, z, m)):6.2f} eV/A")
    print(f"Wrote stopping tables to {here}")


if __name__ == "__main__":
    main()
